spring.application.name=vehicle-rental-system
app.data.users-file=src/main/resources/data/users.txt
app.data.admins-file=src/main/resources/data/admins.txt
app.data.vehicles-file=src/main/resources/data/vehicles.txt
app.data.bookings-file=src/main/resources/data/bookings.txt
app.data.payments-file=src/main/resources/data/payments.txt
app.data.reviews-file=src/main/resources/data/reviews.txt
